//package view;
//
//import controller.ListCntl;
//import model.*;
//
//import javax.swing.*;
//import java.time.LocalDateTime;
//import java.util.Scanner;
//
//public class CustomerUI extends JFrame {
//
//    private ListCntl theListCntl;
//
//
//    public CustomerUI(ListCntl listCntl) {
//        this.theListCntl = listCntl;
//        initComponents();
//        //this.retrieveListOfOrdersView();
//        //this.retrieveNewIssueTicketView();
//    }
//
///**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        complaintButton = new javax.swing.JButton();
//        welcomeLabel = new javax.swing.JLabel();
//        orderHistButton = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        complaintButton.setBackground(new java.awt.Color(41,134,204));
//        complaintButton.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
//        complaintButton.setForeground(new java.awt.Color(255, 255, 255));
//        complaintButton.setOpaque(true);
//        complaintButton.setBorderPainted(false);
//        complaintButton.setText("Submit Complaint");
//
//        welcomeLabel.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
//        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        welcomeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
//        welcomeLabel.setText("Welcome, " + theListCntl.getCurrentCustomer().getFirstName() + ".");
//
//        orderHistButton.setBackground(new java.awt.Color(41,134,204));
//        orderHistButton.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
//        orderHistButton.setForeground(new java.awt.Color(255, 255, 255));
//        orderHistButton.setOpaque(true);
//        orderHistButton.setBorderPainted(false);
//        orderHistButton.setText("View Order History");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(orderHistButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(complaintButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(35, 35, 35)
//                .addComponent(welcomeLabel)
//                .addGap(18, 18, 18)
//                .addComponent(complaintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
//                .addComponent(orderHistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(38, 38, 38))
//        );
//
//        pack();
//    }// </editor-fold>
//
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton complaintButton;
//    private javax.swing.JButton orderHistButton;
//    private javax.swing.JLabel welcomeLabel;
//    // End of variables declaration
//
//}
