/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.*;

import controller.*;
import model.Customer;
import model.Manager;

/**
 *
 * @author amycarr
 */
public class LoginUI extends javax.swing.JFrame {
    
    ListCntl theListCntl;
    /**
     * Creates new form LoginUI
     */
    public LoginUI(ListCntl theListCntl) {
        this.theListCntl = theListCntl;
        initComponents();
        customInitComponents();
        addALButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">    

    private void customInitComponents() {
        ButtonGroup radioGroup = new ButtonGroup();
        radioGroup.add(customerRadio);
        radioGroup.add(managerRadio);
    }
    private void initComponents() {

        customerRadio = new javax.swing.JRadioButton();
        managerRadio = new javax.swing.JRadioButton();
        loginHeaderLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        youAreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerRadio.setFont(new Font("Helvetica", 0, 13));
        customerRadio.setText("Customer");

        managerRadio.setFont(new Font("Helvetica", 0, 13));
        managerRadio.setText("Manager");

        loginHeaderLabel.setFont(new java.awt.Font("Lucida Grande", Font.BOLD, 24)); // NOI18N
        loginHeaderLabel.setText("Login");

        usernameLabel.setFont(new Font("Helvetica", Font.BOLD, 13));
        usernameLabel.setText("Username:");
        
        passwordLabel.setFont(new Font("Helvetica", Font.BOLD, 13));
        passwordLabel.setText("Password:");

        loginButton.setFont(new Font("Helvetica", Font.BOLD, 20));
        loginButton.setForeground(Color.decode("#FFFFFF"));
        loginButton.setBackground(Color.decode("#8CC07D"));
        loginButton.setOpaque(true);
        loginButton.setBorderPainted(false);
        loginButton.setText("Login");

        youAreLabel.setText("You are a:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginHeaderLabel)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(customerRadio)
                        .addGap(18, 18, 18)
                        .addComponent(managerRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(youAreLabel)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(loginHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(youAreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerRadio)
                    .addComponent(customerRadio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(loginButton)
                .addGap(39, 39, 39))
        );
        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton customerRadio;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginHeaderLabel;
    private javax.swing.JRadioButton managerRadio;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel youAreLabel;
    // End of variables declaration            
    
    private void addALButtons() {
        loginButton.addActionListener(e -> {
            if(managerRadio.isSelected()) {
                System.out.println("Manager Selected");
                Manager tempManager = new Manager();
                tempManager.setUsername(usernameField.getText().toString());
                tempManager.setPassword(passwordField.getText().toString());
                theListCntl.requestAuthenticateManager(tempManager);
            }
            else if(customerRadio.isSelected()) {
                System.out.println("Customer Selected");
                Customer tempCustomer = new Customer();
                tempCustomer.setUsername(usernameField.getText().toString());
                tempCustomer.setPassword(passwordField.getText().toString());
                theListCntl.requestAuthenticateCustomer(tempCustomer);
            }
            else {
                theListCntl.requestAuthenticateCustomer(null);
            }
        });
    }
}
